### ISSUE TITLE
Create a non-email verified Firebase user

### ISSUE THREAD

**Issue by weaponsforge** [weaponsforge/my-phonebook#16]
- Create a Firebase user using the Firebase web auth's `createUserWithEmailAndPassword()` method
- Call the custom backend user registration API mentioned on Issue [#12](https://github.com/weaponsforge/my-phonebook/issues/12).

**Comment by vikyw89** [comment]
done :
- Create a Firebase user using the Firebase web auth's createUserWithEmailAndPassword() method

not yet :
- Call the custom backend user registration API mentioned on Issue https://github.com/weaponsforge/my-phonebook/issues/12.
