### ISSUE TITLE
View Contact Page UI

### ISSUE THREAD

**Issue by weaponsforge** [weaponsforge/my-phonebook#37]
- This page will display the **full name** of a selected Contact: (`first_name` + `middle_name` +  `surname`), `email` and `contact_no`.
- Contact data will be fetched from the Firestore database following the instructions on the Components Issue [#36](https://github.com/weaponsforge/my-phonebook/issues/36) 
- This page will display a DELETE contact button, where pressing the button will trigger the delete contact function mentioned in more detail in the Components Integration, Issue [#38](https://github.com/weaponsforge/my-phonebook/issues/38) 
- This page will display an EXPORT CONTACT button, where pressing the button will export the selected Contact information to a CSV or PDF file, following the Components Integration milestone Issue [#43](https://github.com/weaponsforge/my-phonebook/issues/43)

**Comment by vikyw89** [comment]
merged into contact route/ page

TODO: export functionality
