### ISSUE TITLE
Edit Contact Page UI

### ISSUE THREAD

**Issue by weaponsforge** [weaponsforge/my-phonebook#40]
- This page will display the details of a selected Contact: `first_name`, `middle_name`,  `surname`, `email` and `contact_no` on editable text fields.
- Contact data will be fetched from the Firestore database following the instructions on the Components Integration milestone, Issue [#36](https://github.com/weaponsforge/my-phonebook/issues/36).
- This page will display an UPDATE contact button, where pressing the button will trigger an update contact function mentioned in more detail in the Components Integration, Issue [#39](https://github.com/weaponsforge/my-phonebook/issues/39)

**Comment by vikyw89** [comment]
merged into contact route / page
