### ISSUE TITLE
Search Contacts UI

### ISSUE THREAD

**Issue by weaponsforge** [weaponsforge/my-phonebook#42]
- The search contacts UI will enable users to key-in values for searching a Contact by `first_name`, `middle_name`, `last_name`, or `contact_no` from their list of created Contacts
- It will display a SEARCH button, where pressing the button will search for Contacts following the instructions on the Components Integration milestone, Issue [#41](https://github.com/weaponsforge/my-phonebook/issues/41)
- Filtered results will be displayed on the [View Contacts List Page](https://github.com/weaponsforge/my-phonebook/issues/31)

**Comment by vikyw89** [comment]
integrated into contacts route / page
